version: "3.4"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - 8098:80
        links:
            - php-fpm
        volumes:
            - ./:/var/www/laravel-docker
        networks:
            - u-online
    php-fpm:
        build:
            context: .
            dockerfile: docker/Php-Fpm.Dockerfile
        environment:
            PHP_IDE_CONFIG: "serverName=dev.local"
        volumes:
            - ./:/var/www/laravel-docker
        links:
            - mysql
        networks:
            - u-online
    mysql:
        image: mysql
        ports:
            - 33061:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
        networks:
            - u-online
        volumes:
            - db-data-vol:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - u-online
networks:
    u-online:
